import { Inter, Roboto } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto.variable}`}>
      <body className="font-sans bg-stone-50 text-stone-900 min-h-screen flex flex-col">
        {/* HEADER */}
        <header className="border-b border-stone-200 bg-stone-100/50 backdrop-blur-md sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
            <h2 className="font-roboto font-bold text-2xl tracking-tight text-stone-800">
              PATH<span className="text-amber-700">FINDER</span>
            </h2>
            <nav className="hidden md:flex gap-8 text-sm font-medium text-stone-600">
              <a href="/" className="hover:text-amber-800 transition-colors">
                Home
              </a>
              <a
                href="/visualizer"
                className="hover:text-amber-800 transition-colors"
              >
                Visualizer
              </a>
              <a
                href="https://github.com"
                className="hover:text-amber-800 transition-colors"
              >
                Github
              </a>
            </nav>
          </div>
        </header>
        {/* MAIN CONTENT */}
        <main className="grow">{children}</main>
        {/* FOOTER */}
        <footer className="border-t border-stone-200 bg-brand-dark text-stone-300 py-16">
          <div className="max-w-7xl mx-auto px-6">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-12">
              {/* Brand Column */}
              <div className="col-span-1 md:col-span-1">
                <h3 className="font-roboto font-bold text-xl text-brand-paper mb-4 tracking-tight">
                  PATH<span className="text-brand-ochre">FINDER</span>
                </h3>
                <p className="text-sm text-stone-400 leading-relaxed">
                  A vintage-inspired tool for exploring graph theory and spatial
                  optimization through Dijkstra's Lens.
                </p>
              </div>

              {/* Map Resources */}
              <div>
                <h4 className="font-roboto font-bold text-stone-100 mb-4 text-sm uppercase tracking-widest">
                  Map Resources
                </h4>
                <ul className="space-y-2 text-sm">
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      Grid Settings
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      Legend & Symbols
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      Coordinate Systems
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      Export Map Data
                    </a>
                  </li>
                </ul>
              </div>

              {/* Algorithms */}
              <div>
                <h4 className="font-roboto font-bold text-stone-100 mb-4 text-sm uppercase tracking-widest">
                  Algorithms
                </h4>
                <ul className="space-y-2 text-sm">
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      Dijkstra's (Current)
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      A* Search
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      Breadth-First Search
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      Depth-First Search
                    </a>
                  </li>
                </ul>
              </div>

              {/* Technical */}
              <div>
                <h4 className="font-roboto font-bold text-stone-100 mb-4 text-sm uppercase tracking-widest">
                  Technical
                </h4>
                <ul className="space-y-2 text-sm">
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      Documentation
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      API Reference
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      GitHub Repository
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      className="hover:text-brand-ochre transition-colors"
                    >
                      License
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            {/* Bottom Bar */}
            <div className="pt-8 border-t border-stone-800 flex flex-col md:flex-row justify-between items-center gap-4">
              <p className="text-xs text-stone-500 uppercase tracking-tighter">
                &copy; {new Date().getFullYear()} Pathfinder Lab. All rights
                reserved.
              </p>
              <div className="flex gap-6 text-xs text-stone-500 underline underline-offset-4">
                <a href="#" className="hover:text-stone-300">
                  Privacy Policy
                </a>
                <a href="#" className="hover:text-stone-300">
                  Terms of Service
                </a>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
