import { GridProvider } from "@/context/GridContext";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto.variable}`}>
      <body className="font-sans bg-stone-50 text-stone-900 min-h-screen flex flex-col">
        <GridProvider>
          <header className="border-b border-stone-200 bg-stone-100/50 backdrop-blur-md sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
              <Link
                href="/"
                className="font-roboto font-bold text-2xl tracking-tight text-stone-800"
              >
                PATH<span className="text-amber-700">FINDER</span>
              </Link>
              <nav className="hidden md:flex gap-8 text-sm font-bold tracking-widest uppercase items-center">
                <Link
                  href="/"
                  className="hover:text-brand-earth transition-colors"
                >
                  Home
                </Link>
                <Link
                  href="/visualizer"
                  className="px-4 py-2 bg-brand-dark text-brand-paper rounded hover:bg-brand-earth transition-all"
                >
                  Visualizer
                </Link>
                <Link
                  href="/map-engine"
                  className="px-4 py-2 bg-brand-earth text-brand-paper rounded hover:bg-brand-dark transition-all"
                >
                  Map Engine
                </Link>
                <a
                  href="https://github.com/DLGAquilon/practice-map-api-.git"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 hover:text-brand-earth transition-colors"
                >
                  Github
                  <svg
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.28 1.15-.28 2.35 0 3.5-.73 1.02-1.08 2.25-1 3.5 0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"></path>
                    <path d="M9 18c-4.51 2-5-2-7-2"></path>
                  </svg>
                </a>
                <Link href="/settings" className="hover:text-brand-earth transition-colors">
                  Settings
                </Link>
              </nav>
            </div>
          </header>

          {/* MAIN CONTENT */}
          <main className="grow">{children}</main>

          {/* FOOTER */}
          <footer className="border-t border-stone-200 bg-brand-dark text-stone-300 py-16">
            <div className="max-w-7xl mx-auto px-6">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-12 mb-12">
                {/* Brand Column */}
                <div className="col-span-1 md:col-span-1">
                  <h3 className="font-roboto font-bold text-xl text-brand-paper mb-4 tracking-tight">
                    PATH<span className="text-brand-ochre">FINDER</span>
                  </h3>
                  <p className="text-sm text-stone-400 leading-relaxed">
                    A vintage-inspired tool for exploring graph theory and
                    spatial optimization through Dijkstra's Lens.
                  </p>
                </div>

                {/* Map Resources */}
                <div>
                  <h4 className="font-roboto font-bold text-stone-100 mb-4 text-sm uppercase tracking-widest">
                    Map Resources
                  </h4>
                  <ul className="space-y-2 text-sm">
                    <li>
                      <a
                        href="/settings"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        Grid Settings
                      </a>
                    </li>
                    <li>
                      <a
                        href="/logic#legend"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        Legend & Symbols
                      </a>
                    </li>
                    <li>
                      <a
                        href="/coordinates"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        Coordinate Systems
                      </a>
                    </li>
                    <li>
                      <a
                        href="/export"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        Export Map Data
                      </a>
                    </li>
                  </ul>
                </div>

                {/* Algorithms */}
                <div>
                  <h4 className="font-roboto font-bold text-stone-100 mb-4 text-sm uppercase tracking-widest">
                    Algorithms
                  </h4>
                  <ul className="space-y-2 text-sm">
                    <li>
                      <a
                        href="/visualizer"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        Dijkstra's (Current)
                      </a>
                    </li>
                    <li>
                      <a
                        href="/map-engine"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        A* Search
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        Breadth-First Search
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        Depth-First Search
                      </a>
                    </li>
                  </ul>
                </div>

                {/* Technical */}
                <div>
                  <h4 className="font-roboto font-bold text-stone-100 mb-4 text-sm uppercase tracking-widest">
                    Technical
                  </h4>
                  <ul className="space-y-2 text-sm">
                    <li>
                      <a
                        href="/logic"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        Documentation
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        API Reference
                      </a>
                    </li>
                    <li>
                      <a
                        href="https://github.com/DLGAquilon/practice-map-api-.git"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        GitHub Repository
                      </a>
                    </li>
                    <li>
                      <a
                        href="#"
                        className="hover:text-brand-ochre transition-colors"
                      >
                        License
                      </a>
                    </li>
                  </ul>
                </div>
              </div>

              {/* Bottom Bar */}
              <div className="pt-8 border-t border-stone-800 flex flex-col md:flex-row justify-between items-center gap-4">
                <p className="text-xs text-stone-500 uppercase tracking-tighter">
                  &copy; {new Date().getFullYear()} Pathfinder Lab. All rights
                  reserved.
                </p>
                <div className="flex gap-6 text-xs text-stone-500 underline underline-offset-4">
                  <a href="#" className="hover:text-stone-300">
                    Privacy Policy
                  </a>
                  <a href="#" className="hover:text-stone-300">
                    Terms of Service
                  </a>
                </div>
              </div>
            </div>
          </footer>
        </GridProvider>
      </body>
    </html>
  );
}
